### ISSUE TITLE
Nautilus on GNOME 45 looks broken

### ISSUE THREAD

**Issue by DannyFatty707** [witalihirsch/Mono-gtk-theme#51]
![Screenshot from 2023-10-10 14-07-59](https://github.com/witalihirsch/Mono-gtk-theme/assets/96933224/d056404f-0de9-4123-b2f8-3fb3a4a23d48)
After upgrading to GNOME 45, Nautilus seems broken with the background's transparency. All other GTK4 apps work fine.
![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/96933224/f7a79262-6784-45fc-92c6-c2f261073cab)
For example, Easy Effects (which is on GTK4) works fine with no issues.

**Comment by kschat** [comment]
I was able to workaround this by adding the following CSS to `~/.config/gtk-4.0/gtk.css`:

```css
/* Temp workaround */
.nautilus-window .content-pane {
    background-color: rgb(245, 245, 245);
}
```

This will at least make Nautilus usable until a proper patch is applied.

**Comment by DannyFatty707** [comment]
> I was able to workaround this by adding the following CSS to `~/.config/gtk-4.0/gtk.css`:
> 
> ```css
> /* Temp workaround */
> .nautilus-window .content-pane {
>     background-color: rgb(245, 245, 245);
> }
> ```
> 
> This will at least make Nautilus usable until a proper patch is applied.

![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/96933224/10c6df85-e89b-426b-8022-2969b6a14ea9)
It works, but it's just for the light mode. I'm on dark. Can you make one for dark mode?

Update: I've now modified kschat's workaround for Mono's Dark mode:

/* Temp workaround */
.nautilus-window .content-pane {
    background-color: rgb(42, 42, 42);
}

You need to replace 245 with 42 for dark mode, or use 245 if you're on light mode.

![image](https://github.com/witalihirsch/Mono-gtk-theme/assets/96933224/c25a081a-8a33-4b24-8d44-5844d8dfa7e5)

As you can see here, it looks better now.

**Comment by 4JX** [comment]
In my case the sidebar was also transparent, so I needed an extra selector
```css
.nautilus-window .content-pane,
.nautilus-window .sidebar-pane {
    background-color: rgb(42, 42, 42);
}
```

Though I'm pretty sure `#252525` is the de-facto dark background color and `#f0f0f0` the light mode one
